version: '3'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./src:/data
    environment:
      PORT: 8080
      WORKERS: 4
      THREADS: 1
      REDIS_HOST: redis
      REDIS_PORT: 6379
      GUNICORN_CMD_ARGS: "--reload"
      PYTHONUNBUFFERED: "TRUE"
    restart: always
  redis:
    image: "redis:6.0"
  mongo:
    image: "mongo:6"