name: Keepalive Workflows
on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  create-keepalive-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create Keepalive Commit
        uses: gautamkrishnar/keepalive-workflow@master
